### ISSUE TITLE
Determine cause of null task in wait list

### ISSUE THREAD

**Issue by Astaelan** [signalwire/signalwire-dotnet#80]
```
Unhandled Exception: System.ArgumentException: The tasks array included at least one null element.
Parameter name: tasks
   at System.Threading.Tasks.Task.WaitAnyCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Blade.UpstreamSession.TaskWorker() in /signalwire-dotnet/signalwire-dotnet/Relay/Blade/UpstreamSession.cs:line 356
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

Figure out how this is happening, it happens rarely in tests but has now become an issue on internal services. Further investigation on how this happens is required.

This is affecting internal services such as registrar.

**Comment by Astaelan** [comment]
This may be fixed in PR #82 
Further testing is required.
